// flow-typed signature: 1e207e0c207958b48aa093d5b55cf37e
// flow-typed version: <<STUB>>/constitute_v1.6.2/flow_v0.165.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'constitute'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'constitute' {
  declare export class Container {
    bindValue: <TValue>(string, TValue) => void;
    bindClass: <TService>(string, TService, array?: Array<string>) => void;
    bindMethod: <TService, TType>(
      string,
      (TType) => Object,
      array?: Array<string>,
    ) => void;
    constitute: <TResult>(string) => TResult;
    bindAlias: <TService>(string, TService) => void;
  }
}
