on:
  push:
    branches: dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm ci --include=optional
      - run: npm run build:all
      # - run: npm run test:all
      - name: Publish @brewskey/spark-protocol
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_PUBLISH }}
          access: public
          package: ./packages/spark-protocol
      - name: Publish @brewskey/spark-server
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_PUBLISH }}
          access: public
